vrpn_client_node:
  ros__parameters:
    server: 192.168.1.186
    port: 3883
    frame_id: "world"
    use_server_time: false
    refresh_tracker_frequency: 0.2
    update_frequency: 100.0
    num_samples: 100 # TODO: Not currently used, just hardcoded.
